#!/usr/bin/env bash
# installs an nginx severer amd configures ut
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html
sudo echo "Hello World!" > /var/www/html/index.html
sudo nginx -s reload
