#!/usr/bin/env bash
#prinys numbers but replaces 4 and 8
var=1
while [ $var -lt 11 ]
do
	if [ $var -eq 4 ]
	then
		echo "bad luck"
	elif [ $var -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	var=$((var + 1))
done
