#!/usr/bin/env bash
var=1
while [ $var -lt 21 ]
do
	echo $var
	if [ $var -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $var -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $var -eq 17 ]
	then
		echo "bad luck from Italy"
	fi
	var=$((var + 1))
done